USE [BW_BE_S3_Ecommerce]
GO

/****** Object:  Table [dbo].[Ruolo]    Script Date: 19/02/2024 12:18:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Ruolo](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Titolo] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_Ruolo] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

